{{- if .Values.gsm.enabled }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-gsm-secret
  namespace: {{ .Values.namespace }}
spec:
    provider: gcp
    secretObjects:
    - data:
      {{- range $key, $val := .Values.gsm.secrets }}
      {{- if eq $val "" }}
      - key: {{ $key }}                      
        objectName: {{ $key }}
      {{- end }}
      {{- end }}
      secretName: {{ .Release.Name }}-gsm-secret
      type: Opaque   
    parameters:
      secrets: |
      {{- range $key, $val := .Values.gsm.secrets }}
      {{- if eq $val "" }}
        - resourceName: "projects/{{ $.Values.projectId }}/secrets/{{ $key }}/versions/{{ $.Values.gsm.secretVersion | default "latest" }}"
          fileName: {{ $key }}
      {{- end }}
      {{- end }}
{{- end }}
